### ISSUE TITLE
Multiple GSC Sites Verified

### ISSUE THREAD

**Issue by tconte252** [PromInc/organic-search-analytics#27] opened 2016-06-27 01:09 UTC
Hi Brian - I work at an agency and came across this solution not too long ago. I was able to resolve my connection issues but when I import data I get "0 records" were imported.

Since I'm not hosting this platform on the same domain as the verified sites, does this limit my ability o extract the data?

**Comment by PromInc** [comment] 2016-06-27 01:53
Hi Tom,

Issue #26 (0 records successfully imported) raised this same issue.  I'm still not sure what the source of the issue is - there were some thoughts I came across in that issue that you can try.  Ultimately the reporter of that issue indicated that using an older version resulted in success for him.  I don't like that answer personally, but haven't had a chance to circle back to look deeper into it.

As to your question, no, the domain that the platform is hosted on has no bearing on it's functionality.  As long as you have PHP and MySQL on a server it should perform just fine.  This is just a bug that some are experiencing.  I wonder if it's related to the PHP version?  Version 5.4.1 or greater is required  I haven't been able to recreate the same issue as the other report.

**Comment by tconte252** [comment] 2016-06-28 01:01
Thanks, Brian. It looks issue #26 was solved by downgrading to version 2.3.7. I will attempt the same and report back.

**Comment by tconte252** [comment] 2016-06-28 01:10
Confirmed, downgrading from 2.4 to 2.3.7 solved the issue.

**Comment by PromInc** [comment] 2016-07-01 12:01
Please take a look at #26 - this issue should be fixed now.  It would be much appreciated if you'd be willing to do testing (as mentioned in #26) to help me confirm that this issue is resolved.  Thank you.

**Comment by PromInc** [comment] 2016-07-07 02:08
Marking closed - resolved by bug fix 2.4.3

**Closed as completed by PromInc** 2016-07-07 02:08 UTC
