### ISSUE TITLE
0 records succesfully imported

### ISSUE THREAD

**Issue by marowi85** [PromInc/organic-search-analytics#26] opened 2016-06-09 11:13 UTC
Hi Brian,

I have just tried to install your Organic Search Analytics Importer and have some issues with it.

I only get the following records when I import the data:

0 records succesfully imported to the database for mydomain.com for date: 2016-06-04

And that for each day.

I could imagine that it has to do with the service account in Googles Developer Console. There are now different types of service accounts, like "App Engine default service account" or "Compute Engine default service account". And each has a different email adress and p12 file.

You can also create a new service account, which again has another email adress and p12 file.

I have tried both engine default service accounts as well as a new one, which I have called "Organic Search Analytics". But there are no records imported.

Is there something I have forgotten?

I would be very grateful for any help.

Manuel

**Comment by PromInc** [comment] 2016-06-09 14:03
Did you follow the directions on how to setup the Google Developer Console access correctly that can be found here - step 6.
https://github.com/PromInc/organic-search-analytics/wiki/Installation

The domain name in your configuration needs to exactly match that of the domain in GSC, so http vs https, www vs non-www etc.  most likely this is your issue.

**Comment by PromInc** [comment] 2016-06-09 14:10
Also of note, I saw that Google recently announced or added the ability to correlate/connect domains in GSC.  This tool does not work with that at this time.  It's on the todo list, but the implementation plan may be different withGoogles recent change.  But as an example, if you want to track http and https data you need to set those up as separate domains in GSC and this OSA tool.  This gives you two reports - one for each protocol.

**Comment by PromInc** [comment] 2016-06-09 14:13
Please report back with if these tips help and/or what you did to solve the issue to help other users and help improve the tool.

**Comment by marowi85** [comment] 2016-06-10 11:17
Hi Brian,

many thanks for your help.

Unfortunately, the issue still persists. It still only imports 0 records succesfully...

I think I have done all from your installation guide. I have enabled the "Google Search Console API", created an "OAuth 2.0 client ID" and "Compute Engine default service account" with the associated p12 key. 

I also added the "XXXXXXXXXXXX-compute@developer.gserviceaccount.com" email adress and the p12 file to the configuration of your tool.

The same email adress has become full access in Googles Search Console.

Here are two screenshots of my Developers Console backend.

![screen1](https://cloud.githubusercontent.com/assets/5469487/15962612/aa22a16e-2f0c-11e6-89ad-805033cb73ba.jpg)
![screen2](https://cloud.githubusercontent.com/assets/5469487/15962617/b06814c8-2f0c-11e6-8c75-d7fff042a9c1.jpg)

Your tool is now also on the same domain (not subdomain), for which I have an Search Console entry.

I don't know what I might have forgotten.

Maybe something with the server configuration? Or the API account itself?

Best regards
Manuel

**Comment by krillesv** [comment] 2016-06-12 07:15
I have the same issue. 
0 records succesfully imported to the database for (mywebsite) for date: 2016-06-07.
I have followed all the configuration steps and checked them twice. Using serive account xxxxxxxx-compute@developer.gserviceaccount.com

**Comment by PromInc** [comment] 2016-06-12 08:12
I've been able to recreate the issue with a new GDC account.  Looks like Google made some changes to GDC that I think is the issue.

Google is actually a actually returning data but the format is different in some way so the import fails.

Working on a fix as time permits with my week old newborn and will update when I can.

**Comment by krillesv** [comment] 2016-06-12 08:55
I totally understand. Could you give me a heads up where in your code to start looking? Maybe I can solve it myself.. or someone else who's seeing this ;)

**Comment by PromInc** [comment] 2016-06-12 16:29
It looks like it's a database architecture issue.  Alter the table search_analytics, setting the default value for average_click_position to NULL.

That should do it - let me know.  I'll have to update the code to set this correctly by default.

**Comment by marowi85** [comment] 2016-06-13 07:55
> Working on a fix as time permits with my week old newborn and will update when I can.

Congratulations on the birth of your baby and best wishes for now and the future! :)

I have changed the devault value for avg_position_click to NULL but the issue still persists.

Now it looks like:
![screen3](https://cloud.githubusercontent.com/assets/5469487/16000437/be8d989c-314c-11e6-9bb4-a01ad05cb9cc.jpg)

**Comment by PromInc** [comment] 2016-06-13 09:25
> Congratulations on the birth of your baby and best wishes for now and the future! :)
> Thanks!!

Lets try making a call directly to the capture script.  Given that this is a self hosted installation, I can't give you the exact URL to that request, but it should look something like the following.  You'll need to set the domain and path to your codebase, domain, and date.  The `mode=return` parameter returns the direct result from Google to your browser - it won't attempt to import the data to the database.  This should return any error that you are getting from Google.

`http://yourdomain.com/organic-search-analytics/data-capture-run.php?type=googleSearchAnalytics&domain=http%3A%2F%2Fyourdomain.com%2F&date=2016-06-05&mode=return`

The desired output would be an object with all of the search analytics data pulled from Google.  This is the direct response from the Google API request.  This tells us if the issue lies within Google or within the codebase.  If the issue is in the communication with Google, then an error of some sort would be displayed.  Let me know what you see here.

More information about this troubleshooting method at: https://github.com/PromInc/organic-search-analytics/wiki/Data-Capture-Parameters

One other thing is that in your GDC screenshots I never saw that you have **Google Search Console API** Enabled.  Make sure this is enabled.  Choose **API Manager** from the top left menu in Google Developer Console for your project and choose the **Enabled APIs** tab.  You want to see this on the list.

**Comment by marowi85** [comment] 2016-06-13 10:00
I have checked the data-capture-run methode and I got a lot of data for 2016-06-05

> object(Google_Service_Webmasters_SearchAnalyticsQueryResponse)#29 (7) { ["collection_key":protected]=> string(4) "rows" ["internal_gapi_mappings":protected]=> array(0) { } ["responseAggregationType"]=> string(10) "byProperty" ["rowsType":protected]=> string(36) "Google_Service_Webmasters_ApiDataRow" ["rowsDataType":protected]=> string(5) "array" ["modelData":protected]=> array(1) { ["rows"]=> array(897) { [0]=> array(5) { ["keys"]=> array(3) { [0]=> string(21) ...

If I capture the data for this day via tool, it shows the 0 records successfully imported.

The Google Search Console API was enabled.

**Comment by PromInc** [comment] 2016-06-13 10:05
What version are you using?  Found in the bottom right corner.

**Comment by marowi85** [comment] 2016-06-13 10:06
ver 2.4.2

**Comment by marowi85** [comment] 2016-06-15 10:03
Hi Brian,

I have just installed an older version (2.3.7) of your tool and this one works for me.

I also compared the imported data with the data from Search Console and everything looks fine! :)

The only thing I have found out, is that the Avg Position gets rounded in your tool.

I have compared it for one specific keyword.

In your tool the Avg Position is 8.00, in Search Console 8,1 and in Googles export the following: ["position"]=> float(8.1428571428571)

Is it possible to round the Avg Position up to the first decimal place?

Best regards
Manuel

**Comment by marowi85** [comment] 2016-06-15 14:39
> In your tool the Avg Position is 8.00, in Search Console 8,1 and in Googles export the following: ["position"]=> float(8.1428571428571)
> Is it possible to round the Avg Position up to the first decimal place?

This was database related.

I just changed the type of avg_position and avg_position_click from int(11) to float and now it's more detailed with two decimal places.

I will continue with the older version and send you a small donation for your work.

**Comment by PromInc** [comment] 2016-07-01 12:00
I believe I have this issue fixed.

2.4.0 introduced a new piece of information - the country code - pulled from GSC.  An upgrade script corrected the database that allowed this to work, but adding this field was missed in the initial setup SQL statement.

I'd appreciate testing from those of you that reported the issue.  I'd suggest doing a clean install of the master repository, using a new database as well.  This full testing will allow us as a team to ensure that this issue is truly corrected allowing the rest of community to benefit from our efforts!

@marowi85 - I appreciate the donation!  Sorry it took me so long to get back to this issue.

**Comment by tconte252** [comment] 2016-07-06 19:04
I was able to download, instal, and successfully capture data using version 2.4.3. Thanks for the fix, Brian!

**Comment by PromInc** [comment] 2016-07-07 02:07
Thanks for the followup @tconte252 .  I'll close this issue (as well as close issue #27 as it's related).

**Closed as completed by PromInc** 2016-07-07 02:07 UTC
